### ISSUE TITLE
Problem with consent.google.com on the links

### ISSUE THREAD

**Issue by alexanderradahl** [LLukas22/Google-News-Feed#2]
Hi!

I'm trying to resolve the internal links from Google news like this:
`def scrape_headlines(keyword):
    gnf = GoogleNewsFeed(language='en', country='US', resolve_internal_links=True)
    results = gnf.query(keyword)

    headlines_links = {}

    for result in results:
        title = result.title
        link = result.link
        headlines_links[title] = link

    return headlines_links`

But keep getting errors like this when I want to get the article content through newspaper3k:
`Error getting article content for https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMiSGh0dHBzOi8vY2Euc3R5bGUueWFob28uY29tL29wcmFoLW9uY2UtZGVlbWVkLWJ1dHRlcnktc29mdC0xMjMwMDA3ODcuaHRtbNIBUGh0dHBzOi8vY2Euc3R5bGUueWFob28uY29tL2FtcGh0bWwvb3ByYWgtb25jZS1kZWVtZWQtYnV0dGVyeS1zb2Z0LTEyMzAwMDc4Ny5odG1s?oc%3D5&gl=NO&hl=en-US&cm=2&pc=n&src=1`

It seems like all the links from Google gets sent to consent.google.com. Have you had this problem?

**Comment by LLukas22** [comment]
To be frank, I haven't utilized this library for several months, and there's a possibility that Google may have modified their internal routing. Once I return from work, I'll investigate the issue briefly. If the resolution is straightforward, I will take care of implementing it. However, if the fix is more complex, I'll inform you and it may be necessary for you to devise a workaround. In the event of an actual internal routing change by Google, other libraries may also encounter similar difficulties.

**Comment by LLukas22** [comment]
Indeed, there has been a change in their internal logic. However, this has been addressed and updated in version `1.1.0`, which now correctly resolves the links.

**Comment by alexanderradahl** [comment]
That's great! I actually came up with a different solution as the base64 part of the Google news URL actually hides the re-direct URL, here is my code if you would like to do something similar:
`def get_first_url(original_url: str) -> str:
    encoded_url_prefix = "https://news.google.com/rss/articles/"

    if not original_url.startswith(encoded_url_prefix):
        return original_url  # URL is not a Google News encoded URL

    encoded_url = original_url[len(encoded_url_prefix):].split('?')[0]
    encoded_url += "==="  # Fix incorrect padding
    decoded_bytes = base64.urlsafe_b64decode(encoded_url)

    decoded_url_re = re.compile(rb'^\x08\x13".+?(?P<primary_url>http[^\xd2]+)\xd2\x01')
    match = decoded_url_re.match(decoded_bytes)
    primary_url = match.groupdict()["primary_url"].decode()

    return primary_url`

**Comment by LLukas22** [comment]
Well, that's actually a pretty clever solution, kudos to you for discovering it! If I decide to reboot my news scraper, I might just incorporate your solution into this library. Thanks for sharing!
